export const FIVE_FACTION_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_token", type: "address" },
      { internalType: "address", name: "_mockDeFi", type: "address" },
      { internalType: "uint256", name: "_epochDuration", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyBound", type: "error" },
  { inputs: [], name: "AlreadyClaimed", type: "error" },
  { inputs: [], name: "AmountZero", type: "error" },
  { inputs: [], name: "CanvasCycleNotComplete", type: "error" },
  { inputs: [], name: "ClanLockedInEpoch", type: "error" },
  { inputs: [], name: "DeFiInsolvency", type: "error" },
  { inputs: [], name: "DepositPhaseClosed", type: "error" },
  { inputs: [], name: "EpochLocked", type: "error" },
  { inputs: [], name: "EpochNotEnded", type: "error" },
  { inputs: [], name: "EpochNotResolved", type: "error" },
  { inputs: [], name: "InvalidClan", type: "error" },
  { inputs: [], name: "JoinClanFirst", type: "error" },
  { inputs: [], name: "JoinedAfterEpoch", type: "error" },
  { inputs: [], name: "NoStakeFound", type: "error" },
  { inputs: [], name: "NotWinner", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  { inputs: [], name: "TransferFailed", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "enum FiveFaction.Clan",
        name: "winner",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalGenereralYield",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rollover",
        type: "uint256",
      },
    ],
    name: "CanvasCleared",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "warrior",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum FiveFaction.Clan",
        name: "clan",
        type: "uint8",
      },
    ],
    name: "ClanJoined",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "warrior",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      { indexed: false, internalType: "uint256", name: "ink", type: "uint256" },
    ],
    name: "EternalInkClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "warrior",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum FiveFaction.Clan",
        name: "clan",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
    ],
    name: "InkStaked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "warrior",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "InkWithdrawn",
    type: "event",
  },
  {
    inputs: [],
    name: "DEPOSIT_PHASE_DURATION",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_CLAIM_LOOPS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum FiveFaction.Clan", name: "clan", type: "uint8" },
    ],
    name: "calculateScore",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "clanLockedEpoch",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum FiveFaction.Clan", name: "", type: "uint8" },
    ],
    name: "clanTVL",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "clearCanvas",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "currentEpoch",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "epochDuration",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "epochResults",
    outputs: [
      { internalType: "enum FiveFaction.Clan", name: "winner", type: "uint8" },
      { internalType: "uint256", name: "totalInk", type: "uint256" },
      { internalType: "uint256", name: "winnerTVL", type: "uint256" },
      { internalType: "bool", name: "resolved", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "epochStartTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllClanTVLs",
    outputs: [{ internalType: "uint256[5]", name: "", type: "uint256[5]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllScores",
    outputs: [{ internalType: "int256[5]", name: "", type: "int256[5]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum FiveFaction.Clan", name: "clan", type: "uint8" },
    ],
    name: "getClanPredators",
    outputs: [
      { internalType: "enum FiveFaction.Clan", name: "", type: "uint8" },
      { internalType: "enum FiveFaction.Clan", name: "", type: "uint8" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum FiveFaction.Clan", name: "clan", type: "uint8" },
    ],
    name: "getClanTargets",
    outputs: [
      { internalType: "enum FiveFaction.Clan", name: "", type: "uint8" },
      { internalType: "enum FiveFaction.Clan", name: "", type: "uint8" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getTimeUntilCanvasClears",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalTVL",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "warrior", type: "address" }],
    name: "getWarriorInfo",
    outputs: [
      { internalType: "uint128", name: "amount", type: "uint128" },
      { internalType: "enum FiveFaction.Clan", name: "clan", type: "uint8" },
      { internalType: "uint64", name: "epochJoined", type: "uint64" },
      { internalType: "int256", name: "currentScore", type: "int256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "hasClaimedInk",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum FiveFaction.Clan", name: "clan", type: "uint8" },
    ],
    name: "joinClan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "mockDeFi",
    outputs: [{ internalType: "contract MockDeFi", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "limit", type: "uint256" }],
    name: "processRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rolloverInk",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint128", name: "amount", type: "uint128" }],
    name: "stakeInk",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalPrincipal",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userDeposits",
    outputs: [
      { internalType: "uint128", name: "amount", type: "uint128" },
      { internalType: "uint64", name: "epochJoined", type: "uint64" },
      { internalType: "enum FiveFaction.Clan", name: "clan", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint128", name: "amount", type: "uint128" }],
    name: "withdrawInk",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export default FIVE_FACTION_ABI;
